[workspace]
channels = ["conda-forge"]
name = "cybersecurity_attacks"
platforms = ["win-64","osx-64"]
version = "0.1.0"

[tasks]
# This command runs the entire pipeline
run-pipeline = "python pipeline.py"

# This command runs the Streamlit app
run-app = "python -m streamlit run app.py"

#This command runs the generator for the ascii representation of the directory tree excluding directories and files preceded by '.'
gen-dir-repr = "pwsh -Command './generate_ascii_dir_repr.ps1 ./ -Exclude .*, __pycache__ -Depth 3'"

[dependencies]
python = "3.12.*"
streamlit = ">=1.54.0,<2"
scikit-learn = ">=1.8.0,<2"
numpy = ">=1.21.6,<2.0a0"
matplotlib = ">=3.10.8,<4"
seaborn = ">=0.13.2,<0.14"
user-agents = ">=2.2.0,<3"
folium = ">=0.19.0,<0.20"
streamlit-folium = ">=0.25.0,<0.26"
ipykernel = ">=7.2.0,<8"
django = ">=6.0,<7"
pandas = ">=3.0.1,<4"
requests = ">=2.32.5,<3"
plotly = ">=6.5.0,<7"
geoip2 = ">=4.8.0,<5"
gdal = ">=3.12.2,<4"
pandas-stubs = ">=2.3.3.251201,<3"
pyarrow = ">=22.0.0,<23"
geopandas = ">=1.1.1,<2"
geocoder = ">=1.38.1,<2"
pyrosm = ">=0.6.2,<0.7"
curl = ">=8.17.0,<9"
textstat = ">=0.7.11,<0.8"
nltk = ">=3.9.2,<4"
spacy = ">=3.8.11,<4"
lingua-language-detector = ">=1.3.4,<2"
google-cloud-translate = ">=3.23.0,<4"

[pypi-dependencies]
scipy = "*"
chardet = ">=5.2.0, <6"
charset-normalizer = "*"
ftfy = ">=6.3.1, <7"
yara-python = ">=4.5.4, <5"
ioc-finder = ">=5.0.3, <6"
validators = ">=0.35.0, <0.36"
deep-translator = ">=1.11.4, <2"
prince = ">=0.16.5, <0.17"
pyyaml = "*"
ua-parser = "*"
user-agents = "*"
statsmodels = "*"
